//! Regression tests for the README facts a machine can check (CORELIB_PLAN §9,
//! §10).
//!
//! §9 requires the README to describe the library **as it stands**, and §10
//! requires the repo's perf/bench tooling to be documented. Two of those facts
//! had drifted: a hand-maintained "~92%" line-coverage figure that the CI
//! badge already reports (and that had fallen ~5 points behind the real
//! number), and `benches/run_callgrind.sh`, which shipped and worked but was
//! named nowhere in the "Benchmarks" section.
//!
//! Neither drift is detectable by any other test, so the checks live here and
//! run in the ordinary `cargo test` suite.

use std::fs;

const README: &str = include_str!("../README.md");

/// The heading that opens the section documenting the bench tooling.
const BENCH_HEADING: &str = "## Benchmarks";

/// Body of the section introduced by `heading`, up to the next `## ` heading.
fn section(heading: &str) -> &'static str {
    let start = README
        .find(heading)
        .unwrap_or_else(|| panic!("README has no `{heading}` section"))
        + heading.len();
    let rest = &README[start..];
    match rest.find("\n## ") {
        Some(end) => &rest[..end],
        None => rest,
    }
}

/// Does `line` quote a percentage (`96.68%`, `~92 %`, …)?
fn quotes_a_percentage(line: &str) -> bool {
    let b = line.as_bytes();
    b.iter().enumerate().any(|(i, &c)| {
        c == b'%' && {
            // Walk back over optional spaces, then require at least one digit.
            let mut j = i;
            while j > 0 && b[j - 1] == b' ' {
                j -= 1;
            }
            j > 0 && b[j - 1].is_ascii_digit()
        }
    })
}

/// A coverage number in prose is hand-maintained and silently goes stale — the
/// CI-driven badge is the only place a figure may live.
#[test]
fn coverage_percentage_is_not_hand_maintained_in_prose() {
    for (n, line) in README.lines().enumerate() {
        // The badge itself is generated by the Coverage job on every push.
        if line.contains("shields.io") {
            continue;
        }
        if line.to_ascii_lowercase().contains("coverage") && quotes_a_percentage(line) {
            panic!(
                "README.md:{} states a coverage percentage in prose, which drifts \
                 away from the number CI measures; point at the Coverage badge \
                 instead:\n  {}",
                n + 1,
                line.trim()
            );
        }
    }
}

/// …and the badge that replaces it must actually be there.
#[test]
fn coverage_badge_is_present() {
    // The badge is a Shields.io *endpoint* badge pointing at `coverage.json` on
    // the `badges` branch, so its URL carries the path percent-encoded.
    assert!(
        README
            .lines()
            .any(|l| l.contains("shields.io/endpoint") && l.contains("coverage.json")),
        "the README must carry the CI-driven Coverage badge, since it is the \
         only place the coverage figure is stated"
    );
}

/// Every script the repo ships is a documented tool (§10): perf, bench and the
/// Callgrind runner, plus the footprint tool.
#[test]
fn every_shipped_script_is_named_in_the_readme() {
    for dir in ["benches", "tools"] {
        let mut found_any = false;
        for entry in fs::read_dir(dir).expect("script directory") {
            let path = entry.expect("dir entry").path();
            if path.extension().and_then(|e| e.to_str()) != Some("sh") {
                continue;
            }
            found_any = true;
            let name = path.file_name().unwrap().to_str().unwrap();
            let reference = format!("{dir}/{name}");
            assert!(
                README.contains(&reference),
                "`{reference}` ships in the repo but the README never names it; \
                 an undiscoverable tool is an undocumented one (§10)"
            );
        }
        assert!(found_any, "expected at least one shell tool in `{dir}/`");
    }
}

/// All three workload tools belong in the "Benchmarks" section, where a reader
/// looking for them will be — not scattered elsewhere in the file.
#[test]
fn benchmarks_section_documents_all_three_tools() {
    let body = section(BENCH_HEADING);
    for tool in [
        "cargo bench --bench perf",
        "cargo bench --bench bench",
        "benches/run_callgrind.sh",
    ] {
        assert!(
            body.contains(tool),
            "the `{BENCH_HEADING}` section does not document `{tool}`"
        );
    }
}
