//! The README's `### Code generator` example, as code that compiles and runs —
//! and a check that the README still shows exactly this code.
//!
//! A hand-written example in a Markdown file stops matching the API the moment
//! the API moves, and nothing notices until a reader copies it. Here the example
//! is real Rust the compiler and the test binary see, and the mirror check below
//! fails if the README's fenced block and this file ever disagree. Nothing
//! asserts what the README *says* — only that the code in it is this code, and
//! that this code works.

// --- 8< --- README `### Code generator` -------------------------------------

use sofab::{Flush, Handoff, IStream, Id, OStream, Result, Signed, Visitor};

// generated by: sofabgen --lang rust (no_std profile)
#[derive(Default)]
struct Point {
    x: i64,
    y: i64,
}

impl Point {
    /// Worst-case encoded size, so a caller can size its buffer at compile time.
    const MAX_SIZE: usize = 22;

    // --- streaming out: write the fields into any output stream --------------
    fn serialize<'b, F: Flush, H: Handoff<'b>>(&self, os: &mut OStream<'b, F, H>) -> Result<()> {
        os.write_signed(1, self.x)?;
        os.write_signed(2, self.y)
    }

    // --- one-shot: a thin wrapper over the streaming pair --------------------
    fn encode(&self, buf: &mut [u8]) -> Result<usize> {
        let mut os = OStream::new(buf);
        self.serialize(&mut os)?;
        Ok(os.bytes_used())
    }

    // --- streaming in: the reader the caller feeds chunks to -----------------
    fn decoder() -> PointDecoder {
        PointDecoder::default()
    }

    fn decode(bytes: &[u8]) -> Result<Self> {
        let mut d = Point::decoder();
        d.feed(bytes)?;
        Ok(d.value)
    }
}

// `deserialize` — the per-field hook the decoder calls.
impl Visitor for Point {
    fn signed(&mut self, id: Id, v: Signed) {
        match id {
            1 => self.x = v,
            2 => self.y = v,
            _ => {}
        }
    }
}

#[derive(Default)]
struct PointDecoder {
    istream: IStream,
    value: Point,
}

impl PointDecoder {
    /// Feed the next chunk. `Err(Error::Incomplete)` means "more to come".
    fn feed(&mut self, chunk: &[u8]) -> Result<()> {
        self.istream.feed(chunk, &mut self.value)
    }
    /// What has decoded so far; complete once `feed` returned `Ok(())`.
    fn value(&self) -> &Point {
        &self.value
    }
}

// --- >8 --- end of the mirrored block ---------------------------------------

/// The example round-trips — through the one-shot pair and through the streaming
/// one, into a buffer the caller sized: the claims the README makes about
/// generated code on this profile.
#[test]
fn the_readme_generator_example_runs_and_round_trips() {
    let mut buf = [0u8; Point::MAX_SIZE];
    let n = Point { x: 3, y: 4 }.encode(&mut buf).unwrap();
    let got = Point::decode(&buf[..n]).unwrap();
    assert_eq!((got.x, got.y), (3, 4));

    // The streaming pair: `serialize` writes the same bytes into a stream the
    // caller owns, and `decoder()` reads them back one byte at a time — the
    // streaming guarantee the profile exists for.
    let mut streamed = [0u8; Point::MAX_SIZE];
    let m = {
        let mut os = OStream::new(&mut streamed);
        Point { x: 3, y: 4 }.serialize(&mut os).unwrap();
        os.bytes_used()
    };
    assert_eq!(&streamed[..m], &buf[..n]);

    let mut d = Point::decoder();
    for (i, b) in streamed[..m].iter().enumerate() {
        let last = i + 1 == m;
        match d.feed(core::slice::from_ref(b)) {
            Ok(()) => {}
            // A chunk that ends inside a field is INCOMPLETE, not an error;
            // only the final feed has to report a whole message.
            Err(sofab::Error::Incomplete) if !last => {}
            other => panic!("feed({i}) = {other:?}"),
        }
    }
    assert_eq!((d.value().x, d.value().y), (3, 4));
}

/// Every line of the README's Rust example must stand, in order, in this file.
/// A README that drifts from the compiled example fails here rather than in a
/// reader's editor.
#[test]
fn the_readme_shows_the_code_this_file_compiles() {
    const README: &str = include_str!("../README.md");
    const SELF: &str = include_str!("readme_example_tests.rs");

    let block = rust_block_of(README, "### Code generator");
    let mut at = 0usize;
    for line in block.lines() {
        let line = line.trim();
        // What follows is statement code; it lives in the test above.
        if line.starts_with("let mut buf = [0u8; Point::MAX_SIZE];") {
            break;
        }
        if line.is_empty() {
            continue;
        }
        match SELF[at..].find(line) {
            Some(i) => at += i + line.len(),
            None => panic!(
                "README shows a line this file does not compile \
                 (or shows it out of order):\n\t{line}"
            ),
        }
    }
}

/// The first ```rust fence inside the named section.
fn rust_block_of<'a>(doc: &'a str, heading: &str) -> &'a str {
    let i = doc.find(heading).expect("README has no such section");
    let rest = &doc[i..];
    let rest = match rest[heading.len()..].find("\n## ") {
        Some(e) => &rest[..heading.len() + e],
        None => rest,
    };
    let s = rest
        .find("```rust")
        .expect("section has no ```rust example")
        + "```rust".len();
    let rest = &rest[s..];
    let e = rest.find("```").expect("unterminated code fence");
    &rest[..e]
}
